### ISSUE TITLE
NUNCA MAIS DAR PUSH DO WINDOWS

### ISSUE THREAD

**Issue by marcelmendonca** [topicos20152/WEB#24]
PORQUE UM SIMPLES GIT STATUS MOSTRA QUE TUDO FOI DELETADO PQ SIM.

DANDO ROLLBACK E LIGANDO UM LINUX ZZZZ

**Comment by marcelmendonca** [comment]
EU N CONSIGO DAR RESET DE NENHUM TIPO E TENHO PROVA EM 20 MINUTOS SOCORRO TIME

**Comment by marcelmendonca** [comment]
@hugoandregg @luanfonceca @adelinosegundo @wendellpbarreto help pls

**Comment by marcelmendonca** [comment]
@wendellpbarreto vc tinha razão. Windows não presta.

**Comment by luanfonceca** [comment]
já tentou `git checkout -- .` ?

**Comment by marcelmendonca** [comment]
Renato conseguiu dar um push da versão dele, que era a mais recente. Todas as  minhas alterações são obsoletas e nunca mais serão pushadas. Vou me reunir com Hugo amanhã pra trabalhar nas atividades que ficamos de dividir.
Obrigado @luanfonceca 
Desculpa, pessoal.
