### ISSUE TITLE
Erro ao renderizar index

### ISSUE THREAD

**Issue by adelinosegundo** [topicos20152/WEB#9]
![screen shot 2015-10-21 at 12 54 29 pm](https://cloud.githubusercontent.com/assets/3672438/10642202/f7014156-77f2-11e5-8e5a-c375728df5dc.png)

**Comment by wendellpbarreto** [comment]
@adelinosegundo, o erro foi corrigido. O motivo do não carregamento correto da página foi o fato de termos colocado por engano a pasta bower_components no .gitignore.
